### ISSUE TITLE
 按你写的3.7.1可行

### ISSUE THREAD

**Issue by bishen** [aliothor/Windows-Install-Rust-Gdal-Tutorial#1]
尝试3.8.1，没成功

**Comment by aliothor** [comment]
> 尝试3.8.1，没成功

好的，我看看3.8版本有什么问题

**Comment by z954134** [comment]
首先非常感谢,试了3.8.1也是没成功，请问查到原因了吗？

**Comment by aliothor** [comment]
> 首先非常感谢,试了3.8.1也是没成功，请问查到原因了吗？

#### 3.8版本无法使用是因为官方还没有发布rust gdal的新版本，你可以下载预构建的3.8版本文件放在你的cargo缓存里，操作步骤如下
1.  下载官方预构建的文件，https://github.com/georust/gdal/blob/master/gdal-sys/prebuilt-bindings/gdal_3.8.rs
2. 找到电脑上的cargo缓存地址，如：C:\Users\xxx\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\gdal-sys-0.9.1\prebuilt-bindings,将下载好的文件放进去就可以了
![image](https://github.com/aliothor/Windows-Install-Rust-Gdal-Tutorial/assets/60435548/2eb1df46-bce1-45ba-a284-c66f497293f4)

**Comment by aliothor** [comment]
#### 请注意，由于配置了cargo代理，不同机器上的cargo缓存地址可能不同，请注意缓存目录的路径

![PixPin_2024-02-05_14-18-07](https://github.com/aliothor/Windows-Install-Rust-Gdal-Tutorial/assets/60435548/cfc6f43f-a31d-4dc0-8892-04e0fa9d03a3)

**Comment by z954134** [comment]
非常感谢解答，但我实验过程中出现 fatal error LNK1181: cannot open input file 'gdal.lib'这个错误，好奇怪啊

**Comment by qq1469617613** [comment]
> 非常感谢解答，但我实验过程中出现 fatal error LNK1181: cannot open input file 'gdal.lib'这个错误，好奇怪啊

今天我也遇到了这个问题  我的解决方案是   进gdal安装目录 例如：C:/gdal/release-1930-x64-gdal-3-9-1-mapserver-8-2-0/lib  执行 copy gdal_i.lib gdal.lib  完美解决
